### PR TITLE
Updated Jupyter Notebook/Dockerfile to manim6

### PR DESCRIPTION
**Pull request by PaulCMurdoch**
I updated the Dockerfile to load Manim6 and I updated the examples to compile without any warnings.

### CODE REVIEW

**Comment by PaulCMurdoch** [comment]
The mybinder page builds correctly.

**Comment by behackl** [comment]
Thank you for updating the file, much appreciated! Do you have a link with the updated binder somewhere to quickly verify that everything works as expected?

**Comment by PaulCMurdoch** [comment]
> Thank you for updating the file, much appreciated! Do you have a link with the updated binder somewhere to quickly verify that everything works as expected?

No problem. It should look like [this](https://mybinder.org/v2/gh/PaulCMurdoch/jupyter_examples/update?filepath=basic_example_scenes.ipynb).

**Comment by behackl** [comment]
Great! Thank you!

**Pull request merged**
